import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';import{Script}from'node:vm';
const html=await readFile('worker/page.html','utf8');const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new Script(script);const app=await import('../dist/server/index.js');assert.equal(typeof app.default.fetch,'function');
assert(html.includes('<script type="application/json" id="boot">'),'marcador de boot ausente na página');
const routes={'/criar/idade':0,'/criar/foto':1,'/criar/tema':2,'/criar/sentimentos':3,'/criar/estilo':4,'/criar/estrela':5,'/criar/objetivo':6,'/criar/personagens':7,'/criar/idioma':8,'/criar/dedicatoria':9,'/criar/revelacao':10,'/criar/revisao':11};
const slugs=[...html.matchAll(/slug:'([a-z]+)'/g)].map(match=>match[1]);
assert.deepEqual(slugs,Object.keys(routes).map(path=>path.replace('/criar/','')),'slugs do cliente e do servidor estão dessincronizados');
const items=new Map();const env={SHOP_NAME:'FC Livros Mágicos',WHATSAPP_NUMBER:'5511999999999',PRICE_LABEL:'R$ 49,90',PIX_KEY:'pix@exemplo.com',ORDER_SECRET:'segredo-de-teste',ADMIN_TOKEN:'token-de-teste',BUCKET:{get:async key=>items.has(key)?{json:async()=>JSON.parse(items.get(key))}:null,put:async(key,value)=>items.set(key,value),delete:async key=>items.delete(key)}};
const page=await app.default.fetch(new Request('https://example.test/criar/idade'),env);assert.equal(page.status,200);
const pageHtml=await page.text();assert(pageHtml.includes('Para que idade'),'etapa de idade ausente');assert(pageHtml.includes("const languages=[['Português (BR)'")&&!pageHtml.includes("['English")&&!pageHtml.includes("['Español"),'somente Português (BR) disponível');assert(pageHtml.includes('Passo'),'indicador de passos ausente');assert(pageHtml.includes('crop-canvas')&&pageHtml.includes('reveal-range'),'crop ou prévia ausentes');
const cookie=page.headers.get('set-cookie').split(';')[0];
for(const [path,step] of Object.entries(routes)){const response=await app.default.fetch(new Request('https://example.test'+path),env);assert.equal(response.status,200,'rota '+path);const boot=JSON.parse((await response.text()).match(/id="boot">([^<]+)</)[1]);assert.equal(boot.step,step,'passo inicial de '+path);assert.equal(boot.explicit,true,'deep link de '+path)}
const rootBoot=JSON.parse((await (await app.default.fetch(new Request('https://example.test/'),env)).text()).match(/id="boot">([^<]+)</)[1]);assert.equal(rootBoot.explicit,false,'a raiz não deve forçar um passo');
assert.equal((await app.default.fetch(new Request('https://example.test/criar/qualquer'),env)).status,200,'rota desconhecida ainda serve a aplicação');
assert.equal((await app.default.fetch(new Request('https://example.test/criar/foto',{method:'POST'}),env)).status,405);
assert.equal((await app.default.fetch(new Request('https://example.test/criar/tema',{method:'HEAD'}),env)).status,200);
assert.equal((await app.default.fetch(new Request('https://example.test/api/desconhecido'),env)).status,404);
const headers={'Content-Type':'application/json',Origin:'https://example.test',Cookie:cookie};
const draft={data:{name:'Teste',photo:'',cast:[{kind:'Bichinho',name:'Mel',detail:'cachorro',photo:JPG}],language:'Português (BR)',whatsapp:'(85) 99999-9999'},step:11};
await send({method:'PUT',headers,body:JSON.stringify(draft)},200,'salvamento do briefing');
const get=await app.default.fetch(new Request('https://example.test/api/draft',{headers:{Cookie:cookie}}),env);const savedDraft=await get.json();assert.equal(savedDraft.data.language,'Português (BR)','briefing salvo em Português (BR)');
const trackedDrafts=JSON.parse(items.get('briefings/index.json'));assert.equal(trackedDrafts.length,1,'rascunho entrou no índice de carrinhos');assert.equal(trackedDrafts[0].progress,100,'progresso do rascunho registrado');
const other=await app.default.fetch(new Request('https://example.test/api/draft'),env);assert.equal(await other.json(),null,'sessão sem briefing deve receber null');
await send({method:'DELETE',headers},405,'método não permitido no briefing');
await send({method:'PUT',headers:{...headers,Origin:'https://evil.test'},body:JSON.stringify(draft)},403,'origem estrangeira');
await send({method:'PUT',headers:{...headers,'Content-Type':'text/plain'},body:JSON.stringify(draft)},415,'formato inválido');
await send({method:'PUT',headers,body:'{quebrado'},400,'JSON inválido');
await send({method:'PUT',headers,body:JSON.stringify({...draft,step:12})},400,'passo fora do intervalo');
await send({method:'PUT',headers,body:JSON.stringify({data:{...draft.data,cast:[{kind:'Robô',name:'X',detail:'',photo:''}]},step:7})},400,'tipo de personagem inválido');
await send({method:'PUT',headers,body:JSON.stringify({data:{...draft.data,photo:'data:text/html;base64,AAAA'},step:1})},400,'foto com formato inválido');
// ---- Pedido enviado para o WhatsApp da loja ----
const JPG='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AKp//2Q==';
const complete={data:{age:'0 a 5 anos',photo:JPG,outfit:'nova',theme:'Dinossauros',feeling:'Coragem',style:'Aquarela',name:'Levi',gender:'Menino',years:'5',personality:'Curioso',objective:'Guardar esta fase',cast:[{kind:'Bichinho',name:'Mel',detail:'cachorro',photo:''}],language:'Português (BR)',dedicationTitle:'Para Levi',dedication:'Com amor',details:'A praia',whatsapp:'(85) 99999-9999'},step:11};
await send({method:'PUT',headers,body:JSON.stringify(complete)},200,'briefing completo');
const orderResponse=await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers}),env);assert.equal(orderResponse.status,200,'criação do pedido');
const order=await orderResponse.json();
assert.equal(JSON.parse(items.get('briefings/index.json')).length,0,'carrinho removido após virar pedido');
assert.match(order.code,/^[A-F0-9]{12}$/,'código do pedido');
assert(order.link.startsWith('https://example.test/pedido/'),'link do pedido');assert(order.waLink.startsWith('https://wa.me/5511999999999?text='),'link do WhatsApp');
assert(order.summary.includes('Pedido '+order.code)&&order.summary.includes('Levi')&&order.summary.includes('pix@exemplo.com')&&order.summary.includes('(85) 99999-9999'),'resumo do pedido');assert(order.summary.includes('Personagens que vão aparecer')&&order.summary.includes('Mel · Bichinho · cachorro'),'personagens presentes no resumo do WhatsApp');
assert.equal(order.whatsappConfigured,true,'número configurado');assert.equal(order.notified.sent,false,'envio automático desligado sem token');
const orderPage=await app.default.fetch(new Request(order.link),env);assert.equal(orderPage.status,200,'página do pedido');
const orderHtml=await orderPage.text();
assert(orderHtml.includes('Levi')&&orderHtml.includes('pix@exemplo.com')&&orderHtml.includes('(85) 99999-9999')&&orderHtml.includes('Pedido '+order.code),'dados na página do pedido');
assert(orderHtml.includes('data:image/jpeg'),'foto na página do pedido');
assert(pageHtml.includes('FINALIZAR E ENVIAR NO WHATSAPP')&&pageHtml.includes('Seu livro está quase pronto'),'CTA final reforçado');
assert(orderHtml.includes('noindex'),'página do pedido fora de buscadores');
assert.equal((await app.default.fetch(new Request('https://example.test/pedido/'+order.code),env)).status,404,'link sem token deve falhar');
assert.equal((await app.default.fetch(new Request('https://example.test/pedido/'+order.code+'?t=token-de-teste'),env)).status,200,'token de administração abre o pedido');
assert.equal((await app.default.fetch(new Request('https://example.test/api/order',{headers}),env)).status,405,'GET no endpoint do pedido');
assert.equal((await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers:{...headers,Origin:'https://evil.test'}}),env)).status,403,'origem estrangeira no pedido');
const realFetch=globalThis.fetch;const calls=[];
globalThis.fetch=async(target,options)=>{calls.push({url:String(target),options});return new Response(JSON.stringify({id:'media-1'}),{status:200,headers:{'content-type':'application/json'}})};
const autoResponse=await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers}),{...env,WHATSAPP_TOKEN:'token-wa',WHATSAPP_PHONE_ID:'123456'});
globalThis.fetch=realFetch;
const autoOrder=await autoResponse.json();
assert.equal(autoOrder.notified.sent,true,'envio automático pelo Cloud API');assert.equal(calls.length,5,'fotos dos personagens e mensagem enviadas');assert(calls[0].url.includes('/123456/media')&&calls[2].url.includes('/123456/media'),'uploads das fotos principal e do elenco');assert(calls[4].options.body.includes('Pedido '+autoOrder.code)&&calls[4].options.body.includes('Mel'),'texto com personagens enviado');
items.set('briefings/index.json',JSON.stringify([{token:'a'.repeat(64),cartId:'CART000001',createdAt:'2026-09-29T10:00:00.000Z',updatedAt:'2026-09-29T10:30:00.000Z',step:10,progress:92,name:'Ana',whatsapp:'(85) 98888-7777',theme:'Fadas',hasPhoto:true}]));
const painel=await app.default.fetch(new Request('https://example.test/painel?token=token-de-teste'),env);assert.equal(painel.status,200,'painel');const painelHtml=await painel.text();
assert(painelHtml.includes(order.code)&&painelHtml.includes(autoOrder.code),'pedidos listados');
assert(painelHtml.includes('WhatsApp: 5511999999999'),'configuração visível');
assert(painelHtml.includes('(85) 99999-9999')&&painelHtml.includes('Dinossauros'),'painel lista contato e tema do cliente');
assert(painelHtml.includes('/pedido/'+order.code+'?t=token-de-teste'),'painel abre o pedido em modo administrador');
assert(painelHtml.includes('Dashboard de pedidos')&&painelHtml.includes('admin-search')&&painelHtml.includes('admin-status-filter'),'dashboard profissional com busca e filtros');
assert(painelHtml.includes('Pedidos')&&painelHtml.includes('Novos')&&painelHtml.includes('Em produção')&&painelHtml.includes('Pagos')&&painelHtml.includes('Enviados'),'cards de métricas do painel');
assert(painelHtml.includes('Configurações')&&painelHtml.includes('Abrir site'),'navegação profissional do admin');
assert(painelHtml.includes('Carrinhos abandonados')&&painelHtml.includes('CART000001')&&painelHtml.includes('Ana')&&painelHtml.includes('92% preenchido'),'carrinho abandonado visível no admin');assert(painelHtml.includes('Recuperar no WhatsApp'),'ação de recuperação disponível');
const configPage=await app.default.fetch(new Request('https://example.test/painel?token=token-de-teste&view=config'),env);assert.equal(configPage.status,200,'página de configurações');const configHtml=await configPage.text();
for(const block of ['Configurações','Dados da loja','Integrações e segurança','Armazenamento persistente','WhatsApp Cloud API','Segurança'])assert(configHtml.includes(block),'configurações sem: '+block);
const settingsGet=await app.default.fetch(new Request('https://example.test/api/admin/settings?token=token-de-teste'),env);assert.equal(settingsGet.status,200,'leitura das configurações');
const settingsBefore=await settingsGet.json();assert.equal(settingsBefore.shop,'FC Livros Mágicos','nome da loja nas configurações');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/settings?token=errado'),env)).status,403,'token inválido nas configurações');
assert.equal((await app.default.fetch(new Request('https://example.test/painel?token=errado'),env)).status,403,'token inválido no painel');
assert.equal((await app.default.fetch(new Request('https://example.test/painel'),env)).status,403,'painel sem token');
const removed=await app.default.fetch(new Request('https://example.test/painel?token=token-de-teste&apagar='+autoOrder.code),env);assert.equal(removed.status,200,'exclusão do pedido');
assert(!(await removed.text()).includes(autoOrder.code),'pedido removido da lista');assert.equal((await app.default.fetch(new Request(autoOrder.link),env)).status,404,'pedido apagado não abre mais');
// ---- Alteração de status somente para o administrador ----
const statusResponse=await app.default.fetch(new Request('https://example.test/api/admin/status?token=token-de-teste&code='+order.code,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'em produção'})}),env);
assert.equal(statusResponse.status,200,'alteração de status');
const statusPayload=await statusResponse.json();assert.equal(statusPayload.status,'em produção','status atualizado');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/status?token=errado&code='+order.code,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'pago'})}),env)).status,403,'token inválido ao alterar status');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/status?token=token-de-teste&code='+order.code,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'qualquer'})}),env)).status,400,'status inválido recusado');
// ---- Produção (história, prompts e PDF) somente para o administrador ----
const adminPath='/api/admin/book?token=token-de-teste&code=';
assert.equal((await app.default.fetch(new Request('https://example.test/api/book',{method:'POST',headers}),env)).status,404,'cliente não gera história');
assert.equal((await app.default.fetch(new Request('https://example.test/api/book/pdf',{headers:{Cookie:cookie}}),env)).status,404,'cliente não baixa PDF');
const adminBook=await (await app.default.fetch(new Request('https://example.test'+adminPath+order.code,{method:'POST',headers:{Origin:'https://example.test'}}),env)).json();
assert.equal(adminBook.story.pages.length,30,'30 páginas');assert.equal(adminBook.story.illustrations.length,14,'14 prompts de ilustração');
assert.equal(adminBook.story.mock,true,'provedor de demonstração');assert(adminBook.story.title.includes('Levi')&&adminBook.story.pages[0].text.includes('Levi'),'nome presente na história');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/book?code='+order.code+'&token=errado',{method:'POST'}),env)).status,403,'token inválido na produção');
const clientView=await (await app.default.fetch(new Request(order.link),env)).text();
for(const leak of ['Briefing completo do cliente','Fotos recebidas','Resumo do pedido','Cenas de produção','admin-generate','Prompts de ilustração','Prompt:','admin-order-status'])assert(!clientView.includes(leak),'material de produção vazou para o cliente: '+leak);
assert(clientView.includes('Levi')&&clientView.includes('pix@exemplo.com'),'cliente continua vendo seus próprios dados');
const adminView=await (await app.default.fetch(new Request('https://example.test/pedido/'+order.code+'?t=token-de-teste'),env)).text();
for(const block of ['Briefing completo do cliente','Personagens que vão aparecer','Resumo do pedido','Cenas de produção','admin-generate','Prompts de ilustração','admin-order-status','Voltar ao painel'])assert(adminView.includes(block),'visão do admin sem: '+block);
const pdfResponse=await app.default.fetch(new Request('https://example.test/api/admin/pdf?token=token-de-teste&code='+order.code),env);assert.equal(pdfResponse.status,200,'PDF do administrador');
assert.equal(pdfResponse.headers.get('content-type'),'application/pdf','tipo do PDF');assert(pdfResponse.headers.get('content-disposition').includes('livro-levi.pdf'),'nome do arquivo do PDF');
const pdfBytes=new Uint8Array(await pdfResponse.arrayBuffer());assert.equal(String.fromCharCode(...pdfBytes.slice(0,5)),'%PDF-','assinatura do PDF');
const pdfContent=new TextDecoder('latin1').decode(pdfBytes);
assert(pdfContent.includes('%%EOF'),'PDF completo');assert(pdfContent.includes('/Subtype /Image'),'foto embutida no PDF');assert(pdfContent.includes('Página 30'),'30 páginas no PDF');
const fallback=await (await app.default.fetch(new Request('https://example.test'+adminPath+order.code,{method:'POST'}),{...env,AI_PROVIDER:'openai'})).json();
assert.equal(fallback.story.mock,true,'sem chave cai no provedor de demonstração');assert(fallback.story.notice.includes('Sem chave'),'aviso de chave ausente');
await send({method:'PUT',headers,body:JSON.stringify({data:{name:'Levi'},step:1})},200,'briefing incompleto');
const incomplete=await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers}),env);assert.equal(incomplete.status,400,'pedido sem briefing completo');
assert((await incomplete.json()).error.includes('Faltam informações'),'mensagem de campos faltantes');
const settingsSave=await app.default.fetch(new Request('https://example.test/api/admin/settings?token=token-de-teste',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://example.test'},body:JSON.stringify({shop:'FC Loja Teste',whatsapp:'85992019111',price:'R$ 59,90',pix:'pix-teste'})}),env);assert.equal(settingsSave.status,200,'salvamento das configurações');
const settingsSaved=await settingsSave.json();assert.equal(settingsSaved.whatsapp,'5585992019111','WhatsApp normalizado nas configurações');
const shopAfter=await (await app.default.fetch(new Request('https://example.test/api/shop'),env)).json();
assert.equal(shopAfter.shop,'FC Loja Teste','nome da loja aplicado');assert.equal(shopAfter.price,'R$ 59,90','preço aplicado');assert.equal(shopAfter.pix,'pix-teste','Pix aplicado');assert.equal(shopAfter.whatsappConfigured,true,'WhatsApp aplicado');
console.log('HTML/JS valid; 12 rotas de passo, deep link, crop/prévia, pedido no WhatsApp, painel e isolamento de sessão verificados.');
async function send(options,expected,label){const response=await app.default.fetch(new Request('https://example.test/api/draft',options),env);assert.equal(response.status,expected,'esperava '+expected+' em '+label+' e recebeu '+response.status)}
