import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';import{Script}from'node:vm';
const html=await readFile('worker/page.html','utf8');const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new Script(script);const app=await import('../dist/server/index.js');assert.equal(typeof app.default.fetch,'function');
assert(html.includes('<script type="application/json" id="boot">'),'marcador de boot ausente na página');
const routes={'/criar/crianca':0,'/criar/historia':1,'/criar/personagens':2,'/criar/personalizacao':3,'/criar/finalizar':4};
const legacyRoutes={'/criar/idade':0,'/criar/foto':0,'/criar/estrela':0,'/criar/tema':1,'/criar/sentimentos':1,'/criar/estilo':1,'/criar/objetivo':3,'/criar/idioma':3,'/criar/dedicatoria':3,'/criar/revelacao':4,'/criar/revisao':4};
const slugs=[...html.matchAll(/slug:'([a-z]+)'/g)].map(match=>match[1]);
assert.deepEqual(slugs,Object.keys(routes).map(path=>path.replace('/criar/','')),'slugs do cliente e do servidor estão dessincronizados');assert.equal(slugs.length,5,'funil deve ter 5 etapas');
const items=new Map();const env={SHOP_NAME:'FC Livros Mágicos',WHATSAPP_NUMBER:'5511999999999',PRICE_LABEL:'R$ 49,90',PIX_KEY:'pix@exemplo.com',PIX_COPY_PASTE:'000201PIXTESTE123456789',ORDER_SECRET:'segredo-de-teste',ADMIN_TOKEN:'token-de-teste',BUCKET:{get:async key=>items.has(key)?{json:async()=>JSON.parse(items.get(key))}:null,put:async(key,value)=>items.set(key,value),delete:async key=>items.delete(key)}};
const page=await app.default.fetch(new Request('https://example.test/criar/crianca'),env);assert.equal(page.status,200);
const pageHtml=await page.text();assert(pageHtml.includes('Conte sobre a criança'),'etapa Criança ausente');const funnelStart=JSON.parse(items.get('analytics/funnel.json'));assert.equal(funnelStart.steps[0],1,'entrada registrada no funil');assert(pageHtml.includes("slug:'crianca'")&&pageHtml.includes("slug:'finalizar'")&&!pageHtml.includes("slug:'sentimentos'")&&!pageHtml.includes("slug:'idioma'"),'somente 5 etapas no funil');assert(pageHtml.includes('visit-count'),'contador de visitas ausente do rodapé');const firstVisitStats=JSON.parse(items.get('analytics/visits.json'));assert.equal(firstVisitStats.total,1,'primeira sessão conta uma visita');assert(pageHtml.includes("const languages=[['Português (BR)'")&&!pageHtml.includes("['English")&&!pageHtml.includes("['Español"),'somente Português (BR) disponível');assert(pageHtml.includes('Passo'),'indicador de passos ausente');assert(pageHtml.includes('crop-canvas')&&pageHtml.includes('reveal-range'),'crop ou prévia ausentes');
const cookie=page.headers.get('set-cookie').split(';')[0];
const quizResponse=await app.default.fetch(new Request('https://example.test/quiz',{headers:{Cookie:cookie}}),env);assert.equal(quizResponse.status,200,'quiz de fotos');
const quizHtml=await quizResponse.text();
for(const style of ['Casal Jeans','Roupas Claras','Roupas Coloridas'])assert(quizHtml.includes(style),'estilo de casal ausente: '+style);
for(const removedStyle of ['Praia Romântica','Social Elegante','Preto & Branco'])assert(!quizHtml.includes(removedStyle),'estilo removido ainda aparece: '+removedStyle);
assert(quizHtml.includes('Escolha um dos 3 estilos profissionais'),'quiz deve mostrar somente 3 estilos de casal');
assert(quizHtml.includes('Escolha a posição'),'quiz explica a seleção das poses do casal');
assert(quizHtml.includes('customerName')&&quizHtml.includes('customerWhatsapp')&&quizHtml.includes('* obrigatório')&&quizHtml.includes('whatsappAlert'),'quiz exige WhatsApp para gerar prévia');
assert(quizHtml.includes('/api/quiz-limit')&&quizHtml.includes('limitNote')&&quizHtml.includes('Pedir liberação no WhatsApp'),'quiz exibe limite e pedido de liberação');
assert(quizHtml.includes('https://d2ol7oe51mr4n9.cloudfront.net/'),'fonte estável do catálogo ausente');
assert(quizHtml.includes('poseThumb')&&quizHtml.includes('catalog-canvas')&&quizHtml.includes('paintCatalogPhotos'),'miniaturas fotograficas das posicoes ausentes');
assert(quizHtml.includes('crop:[0,0,150,200]')&&quizHtml.includes('crop:[450,200,150,200]'),'catalogo deve usar grade JPEG 600x400 com 8 recortes');
await app.default.fetch(new Request('https://example.test/criar/historia',{headers:{Cookie:cookie}}),env);assert.equal(JSON.parse(items.get('analytics/visits.json')).total,1,'mesma sessão não duplica visita');const funnelHistory=JSON.parse(items.get('analytics/funnel.json'));assert.equal(funnelHistory.steps[0],1,'mesma sessão não duplica primeira etapa');assert.equal(funnelHistory.steps[1],1,'avanço para História registrado');await app.default.fetch(new Request('https://example.test/criar/historia',{headers:{Cookie:cookie}}),env);assert.equal(JSON.parse(items.get('analytics/funnel.json')).steps[1],1,'repetir etapa não duplica funil');const visitApi=await (await app.default.fetch(new Request('https://example.test/api/visits',{headers:{Cookie:cookie}}),env)).json();assert.equal(visitApi.total,1,'API pública de visitas');
for(const [path,step] of Object.entries(routes)){const response=await app.default.fetch(new Request('https://example.test'+path),env);assert.equal(response.status,200,'rota '+path);const boot=JSON.parse((await response.text()).match(/id="boot">([^<]+)</)[1]);assert.equal(boot.step,step,'passo inicial de '+path);assert.equal(boot.explicit,true,'deep link de '+path)}
for(const [path,step] of Object.entries(legacyRoutes)){const response=await app.default.fetch(new Request('https://example.test'+path),env);assert.equal(response.status,200,'rota legada '+path);const boot=JSON.parse((await response.text()).match(/id="boot">([^<]+)</)[1]);assert.equal(boot.step,step,'compatibilidade de '+path)}
const rootBoot=JSON.parse((await (await app.default.fetch(new Request('https://example.test/'),env)).text()).match(/id="boot">([^<]+)</)[1]);assert.equal(rootBoot.explicit,false,'a raiz não deve forçar um passo');
assert.equal((await app.default.fetch(new Request('https://example.test/criar/qualquer'),env)).status,200,'rota desconhecida ainda serve a aplicação');
assert.equal((await app.default.fetch(new Request('https://example.test/criar/foto',{method:'POST'}),env)).status,405);
assert.equal((await app.default.fetch(new Request('https://example.test/criar/historia',{method:'HEAD'}),env)).status,200);
assert.equal((await app.default.fetch(new Request('https://example.test/api/desconhecido'),env)).status,404);
const headers={'Content-Type':'application/json',Origin:'https://example.test',Cookie:cookie};
const draft={data:{name:'Teste',photo:'',cast:[{kind:'Bichinho',name:'Mel',detail:'cachorro',photo:''}],language:'Português (BR)',whatsapp:'(85) 99999-9999'},step:4};
await send({method:'PUT',headers,body:JSON.stringify(draft)},200,'salvamento do briefing');
const get=await app.default.fetch(new Request('https://example.test/api/draft',{headers:{Cookie:cookie}}),env);const savedDraft=await get.json();assert.equal(savedDraft.data.language,'Português (BR)','briefing salvo em Português (BR)');
const trackedDrafts=JSON.parse(items.get('briefings/index.json'));assert.equal(trackedDrafts.length,1,'rascunho entrou no índice de carrinhos');assert.equal(trackedDrafts[0].progress,100,'progresso do rascunho registrado');const funnelFinal=JSON.parse(items.get('analytics/funnel.json'));assert(funnelFinal.steps.slice(0,5).every(value=>value>=1),'chegada até Finalizar registrada no funil');
const other=await app.default.fetch(new Request('https://example.test/api/draft'),env);assert.equal(await other.json(),null,'sessão sem briefing deve receber null');
await send({method:'DELETE',headers},405,'método não permitido no briefing');
await send({method:'PUT',headers:{...headers,Origin:'https://evil.test'},body:JSON.stringify(draft)},403,'origem estrangeira');
await send({method:'PUT',headers:{...headers,'Content-Type':'text/plain'},body:JSON.stringify(draft)},415,'formato inválido');
await send({method:'PUT',headers,body:'{quebrado'},400,'JSON inválido');
await send({method:'PUT',headers,body:JSON.stringify({...draft,step:5})},400,'passo fora do intervalo');
await send({method:'PUT',headers,body:JSON.stringify({data:{...draft.data,cast:[{kind:'Robô',name:'X',detail:'',photo:''}]},step:2})},400,'tipo de personagem inválido');
await send({method:'PUT',headers,body:JSON.stringify({data:{...draft.data,photo:'data:text/html;base64,AAAA'},step:0})},400,'foto com formato inválido');
// ---- Pedido enviado para o WhatsApp da loja ----
const JPG='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AKp//2Q==';
for(const style of ['casal_jeans','casal_claras','casal_coloridas','casal_praia','casal_social','casal_pb']){
 const preview=await app.default.fetch(new Request('https://example.test/api/preview',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://example.test',Cookie:cookie},body:JSON.stringify({type:'casal',style,pose:'1',photo:JPG,customerWhatsapp:'(85) 99999-9999'})}),env);
 assert.equal(preview.status,200,'preview aceita estilo '+style);
 const payload=await preview.json();assert.equal(payload.demo,true,'preview sem API usa demonstração '+style);
}
const previewWithoutWhatsapp=await app.default.fetch(new Request('https://example.test/api/preview',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://example.test',Cookie:cookie},body:JSON.stringify({type:'casal',style:'casal_jeans',pose:'1',photo:JPG})}),env);
assert.equal(previewWithoutWhatsapp.status,400,'preview sem WhatsApp deve ser bloqueada');
assert((await previewWithoutWhatsapp.json()).error.includes('WhatsApp'),'erro deve pedir WhatsApp');

const complete={data:{age:'0 a 5 anos',photo:JPG,outfit:'nova',theme:'Dinossauros',feeling:'Coragem',style:'Aquarela',name:'Levi',gender:'Menino',years:'5',personality:'Curioso',objective:'Guardar esta fase',cast:[{kind:'Bichinho',name:'Mel',detail:'cachorro',photo:JPG}],language:'Português (BR)',dedicationTitle:'Para Levi',dedication:'Com amor',details:'A praia',whatsapp:'(85) 99999-9999'},step:4};
await send({method:'PUT',headers,body:JSON.stringify(complete)},200,'briefing completo');
const orderResponse=await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers}),env);assert.equal(orderResponse.status,200,'criação do pedido');
const order=await orderResponse.json();assert(JSON.parse(items.get('analytics/funnel.json')).orders>=1,'pedido convertido registrado no funil');
assert.equal(JSON.parse(items.get('briefings/index.json')).length,0,'carrinho removido após virar pedido');
assert.match(order.code,/^[A-F0-9]{12}$/,'código do pedido');
assert(order.link.startsWith('https://example.test/pedido/'),'link do pedido');assert(order.waLink.startsWith('https://wa.me/5511999999999?text='),'link do WhatsApp');
assert(order.summary.includes('Pedido '+order.code)&&order.summary.includes('Levi')&&order.summary.includes('pix@exemplo.com')&&order.summary.includes('(85) 99999-9999'),'resumo do pedido');assert(order.summary.includes('Personagens que vão aparecer')&&order.summary.includes('Mel · Bichinho · cachorro'),'personagens presentes no resumo do WhatsApp');
assert.equal(order.whatsappConfigured,true,'número configurado');assert.equal(order.pixCopyPaste,'000201PIXTESTE123456789','Pix Copia e Cola retornado no pedido');assert.equal(order.notified.sent,false,'envio automático desligado sem token');
const orderPage=await app.default.fetch(new Request(order.link),env);assert.equal(orderPage.status,200,'página do pedido');
const orderHtml=await orderPage.text();
assert(orderHtml.includes('Levi')&&orderHtml.includes('pix@exemplo.com')&&orderHtml.includes('(85) 99999-9999')&&orderHtml.includes('Pedido '+order.code),'dados na página do pedido');
assert(orderHtml.includes('data:image/jpeg'),'foto na página do pedido');
assert(pageHtml.includes('FINALIZAR E ENVIAR NO WHATSAPP')&&pageHtml.includes('Seu livro está quase pronto'),'CTA final reforçado');assert(pageHtml.includes('PAGAR AGORA VIA PIX')&&pageHtml.includes('pix-code'),'checkout Pix disponível');
assert(orderHtml.includes('noindex'),'página do pedido fora de buscadores');
assert.equal((await app.default.fetch(new Request('https://example.test/pedido/'+order.code),env)).status,404,'link sem token deve falhar');
assert.equal((await app.default.fetch(new Request('https://example.test/pedido/'+order.code+'?t=token-de-teste'),env)).status,200,'token de administração abre o pedido');
assert.equal((await app.default.fetch(new Request('https://example.test/api/order',{headers}),env)).status,405,'GET no endpoint do pedido');
assert.equal((await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers:{...headers,Origin:'https://evil.test'}}),env)).status,403,'origem estrangeira no pedido');
const realFetch=globalThis.fetch;const calls=[];
globalThis.fetch=async(target,options)=>{calls.push({url:String(target),options});return new Response(JSON.stringify({id:'media-1'}),{status:200,headers:{'content-type':'application/json'}})};
const autoResponse=await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers}),{...env,WHATSAPP_TOKEN:'token-wa',WHATSAPP_PHONE_ID:'123456'});
globalThis.fetch=realFetch;
const autoOrder=await autoResponse.json();
assert.equal(autoOrder.notified.sent,true,'envio automático pelo Cloud API');assert.equal(calls.length,5,'fotos dos personagens e mensagem enviadas');assert(calls[0].url.includes('/123456/media')&&calls[2].url.includes('/123456/media'),'uploads das fotos principal e do elenco');assert(calls[4].options.body.includes('Pedido '+autoOrder.code)&&calls[4].options.body.includes('Mel'),'texto com personagens enviado');
items.set('briefings/index.json',JSON.stringify([{token:'a'.repeat(64),cartId:'CART000001',createdAt:'2026-09-29T10:00:00.000Z',updatedAt:'2026-09-29T10:30:00.000Z',step:3,progress:80,name:'Ana',whatsapp:'(85) 98888-7777',theme:'Fadas',hasPhoto:true}]));
const visitsBeforeAdmin=JSON.parse(items.get('analytics/visits.json')).total;
const painel=await app.default.fetch(new Request('https://example.test/painel?token=token-de-teste'),env);assert.equal(painel.status,200,'painel');const painelHtml=await painel.text();assert.equal(JSON.parse(items.get('analytics/visits.json')).total,visitsBeforeAdmin,'painel não conta como visita pública');
assert(painelHtml.includes('Clientes e Prévias')&&painelHtml.includes('quiz-client-search')&&painelHtml.includes('quiz-style-filter')&&painelHtml.includes('quiz-pose-filter'),'painel padrão deve ser o CRM de prévias');
assert(painelHtml.includes('FC Artes Digitais')&&painelHtml.includes('Abrir quiz')&&!painelHtml.includes('Dashboard de pedidos'),'navegação do admin deve ser focada somente em fotos');
const quizClientsPage=await app.default.fetch(new Request('https://example.test/painel?token=token-de-teste&view=quiz-clients'),env);assert.equal(quizClientsPage.status,200,'clientes/fotos do quiz');const quizClientsHtml=await quizClientsPage.text();assert(quizClientsHtml.includes('Clientes e Prévias')&&quizClientsHtml.includes('quiz-client-search')&&quizClientsHtml.includes('quiz-style-filter')&&quizClientsHtml.includes('quiz-pose-filter')&&quizClientsHtml.includes('quiz-date-filter'),'CRM do quiz com filtros');
assert(quizClientsHtml.includes('Prévias hoje')&&quizClientsHtml.includes('Pagaram')&&quizClientsHtml.includes('Entregues'),'CRM mostra indicadores comerciais');
const configPage=await app.default.fetch(new Request('https://example.test/painel?token=token-de-teste&view=config'),env);assert.equal(configPage.status,200,'página de configurações');const configHtml=await configPage.text();
for(const block of ['Configurações','Dados da loja','Integrações e segurança','Armazenamento persistente','WhatsApp Cloud API','Segurança'])assert(configHtml.includes(block),'configurações sem: '+block);
const settingsGet=await app.default.fetch(new Request('https://example.test/api/admin/settings?token=token-de-teste'),env);assert.equal(settingsGet.status,200,'leitura das configurações');
const settingsBefore=await settingsGet.json();assert.equal(settingsBefore.shop,'FC Livros Mágicos','nome da loja nas configurações');assert.equal(settingsBefore.pixCopyPaste,'000201PIXTESTE123456789','Pix Copia e Cola nas configurações');
const limitStatus=await app.default.fetch(new Request('https://example.test/api/quiz-limit',{headers:{Cookie:cookie}}),env);assert.equal(limitStatus.status,200,'consulta do limite de gerações');const limitPayload=await limitStatus.json();assert.equal(limitPayload.dailyLimit,3,'limite diário é 3');assert.equal(limitPayload.cooldownSeconds,180,'intervalo é 3 minutos');

assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/quiz-access?token=errado',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionToken:cookie.split('=')[1],mode:'allowed'})}),env)).status,403,'token inválido no controle de geração');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/quiz-access?token=token-de-teste',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionToken:cookie.split('=')[1],mode:'blocked'})}),env)).status,200,'admin consegue bloquear geração');
const blockedLimit=await (await app.default.fetch(new Request('https://example.test/api/quiz-limit',{headers:{Cookie:cookie}}),env)).json();assert.equal(blockedLimit.mode,'blocked','bloqueio manual persistido');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/quiz-access?token=token-de-teste',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionToken:cookie.split('=')[1],mode:'auto'})}),env)).status,200,'admin consegue voltar ao automático');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/settings?token=errado'),env)).status,403,'token inválido nas configurações');
assert.equal((await app.default.fetch(new Request('https://example.test/painel?token=errado'),env)).status,403,'token inválido no painel');
assert.equal((await app.default.fetch(new Request('https://example.test/painel'),env)).status,403,'painel sem token');
const removed=await app.default.fetch(new Request('https://example.test/painel?token=token-de-teste&apagar='+autoOrder.code),env);assert.equal(removed.status,200,'exclusão do pedido');
assert(!(await removed.text()).includes(autoOrder.code),'pedido removido da lista');assert.equal((await app.default.fetch(new Request(autoOrder.link),env)).status,404,'pedido apagado não abre mais');
// ---- Alteração de status somente para o administrador ----
const statusResponse=await app.default.fetch(new Request('https://example.test/api/admin/status?token=token-de-teste&code='+order.code,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'em produção'})}),env);
assert.equal(statusResponse.status,200,'alteração de status');
const statusPayload=await statusResponse.json();assert.equal(statusPayload.status,'em produção','status atualizado');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/status?token=errado&code='+order.code,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'pago'})}),env)).status,403,'token inválido ao alterar status');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/status?token=token-de-teste&code='+order.code,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'qualquer'})}),env)).status,400,'status inválido recusado');
// ---- Produção (história, prompts e PDF) somente para o administrador ----
const adminPath='/api/admin/book?token=token-de-teste&code=';
assert.equal((await app.default.fetch(new Request('https://example.test/api/book',{method:'POST',headers}),env)).status,404,'cliente não gera história');
assert.equal((await app.default.fetch(new Request('https://example.test/api/book/pdf',{headers:{Cookie:cookie}}),env)).status,404,'cliente não baixa PDF');
const adminBook=await (await app.default.fetch(new Request('https://example.test'+adminPath+order.code,{method:'POST',headers:{Origin:'https://example.test'}}),env)).json();
assert.equal(adminBook.story.pages.length,30,'30 páginas');assert.equal(adminBook.story.illustrations.length,14,'14 prompts de ilustração');
assert.equal(adminBook.story.mock,true,'provedor de demonstração');assert(adminBook.story.title.includes('Levi')&&adminBook.story.pages[0].text.includes('Levi'),'nome presente na história');
assert.equal((await app.default.fetch(new Request('https://example.test/api/admin/book?code='+order.code+'&token=errado',{method:'POST'}),env)).status,403,'token inválido na produção');
const clientView=await (await app.default.fetch(new Request(order.link),env)).text();
for(const leak of ['Briefing completo do cliente','Fotos recebidas','Resumo do pedido','Cenas de produção','admin-generate','Prompts de ilustração','Prompt:','admin-order-status'])assert(!clientView.includes(leak),'material de produção vazou para o cliente: '+leak);
assert(clientView.includes('Levi')&&clientView.includes('pix@exemplo.com'),'cliente continua vendo seus próprios dados');
const adminView=await (await app.default.fetch(new Request('https://example.test/pedido/'+order.code+'?t=token-de-teste'),env)).text();
for(const block of ['Briefing completo do cliente','Personagens que vão aparecer','Resumo do pedido','Cenas de produção','admin-generate','Prompts de ilustração','admin-order-status','Voltar ao painel'])assert(adminView.includes(block),'visão do admin sem: '+block);
const pdfResponse=await app.default.fetch(new Request('https://example.test/api/admin/pdf?token=token-de-teste&code='+order.code),env);assert.equal(pdfResponse.status,200,'PDF do administrador');
assert.equal(pdfResponse.headers.get('content-type'),'application/pdf','tipo do PDF');assert(pdfResponse.headers.get('content-disposition').includes('livro-levi.pdf'),'nome do arquivo do PDF');
const pdfBytes=new Uint8Array(await pdfResponse.arrayBuffer());assert.equal(String.fromCharCode(...pdfBytes.slice(0,5)),'%PDF-','assinatura do PDF');
const pdfContent=new TextDecoder('latin1').decode(pdfBytes);
assert(pdfContent.includes('%%EOF'),'PDF completo');assert(pdfContent.includes('/Subtype /Image'),'foto embutida no PDF');assert(pdfContent.includes('Página 30'),'30 páginas no PDF');
const fallback=await (await app.default.fetch(new Request('https://example.test'+adminPath+order.code,{method:'POST'}),{...env,AI_PROVIDER:'openai'})).json();
assert.equal(fallback.story.mock,true,'sem chave cai no provedor de demonstração');assert(fallback.story.notice.includes('Sem chave'),'aviso de chave ausente');
await send({method:'PUT',headers,body:JSON.stringify({data:{name:'Levi'},step:1})},200,'briefing incompleto');
const incomplete=await app.default.fetch(new Request('https://example.test/api/order',{method:'POST',headers}),env);assert.equal(incomplete.status,400,'pedido sem briefing completo');
assert((await incomplete.json()).error.includes('Faltam informações'),'mensagem de campos faltantes');
const settingsSave=await app.default.fetch(new Request('https://example.test/api/admin/settings?token=token-de-teste',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://example.test'},body:JSON.stringify({shop:'FC Loja Teste',whatsapp:'85992019111',price:'R$ 59,90',pix:'pix-teste',pixCopyPaste:'000201NOVOPIX987654321'})}),env);assert.equal(settingsSave.status,200,'salvamento das configurações');
const settingsSaved=await settingsSave.json();assert.equal(settingsSaved.whatsapp,'5585992019111','WhatsApp normalizado nas configurações');
const shopAfter=await (await app.default.fetch(new Request('https://example.test/api/shop'),env)).json();
assert.equal(shopAfter.shop,'FC Loja Teste','nome da loja aplicado');assert.equal(shopAfter.price,'R$ 59,90','preço aplicado');assert.equal(shopAfter.pix,'pix-teste','Pix aplicado');assert.equal(shopAfter.pixCopyPaste,'000201NOVOPIX987654321','Pix Copia e Cola aplicado');assert.equal(shopAfter.whatsappConfigured,true,'WhatsApp aplicado');
console.log('HTML/JS valid; 12 rotas de passo, deep link, crop/prévia, pedido no WhatsApp, painel e isolamento de sessão verificados.');
async function send(options,expected,label){const response=await app.default.fetch(new Request('https://example.test/api/draft',options),env);assert.equal(response.status,expected,'esperava '+expected+' em '+label+' e recebeu '+response.status)}
