// worker/order.js — pedido do briefing enviado para o WhatsApp da loja.
// Ambiente: WHATSAPP_NUMBER (DDI + DDD + número, só dígitos), SHOP_NAME, PRICE_LABEL, PIX_KEY,
// ORDER_SECRET (assina os links do pedido), ADMIN_TOKEN (painel e exclusão) e,
// opcionalmente, WHATSAPP_TOKEN + WHATSAPP_PHONE_ID para enviar o pedido pelo WhatsApp Cloud API.
const ORDER_STATUSES=['novo','em produção','pago','enviado','cancelado'];
const orderSettings=env=>{const source=env||{};return {shop:cleanText(source.SHOP_NAME)||'FC Livros Mágicos',whatsapp:cleanText(source.WHATSAPP_NUMBER).replace(/[^0-9]/g,''),price:cleanText(source.PRICE_LABEL)||'R$ 49,90',pix:cleanText(source.PIX_KEY),secret:cleanText(source.ORDER_SECRET),admin:cleanText(source.ADMIN_TOKEN),token:cleanText(source.WHATSAPP_TOKEN),phoneId:cleanText(source.WHATSAPP_PHONE_ID)}};
const orderCode=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),byte=>byte.toString(16).padStart(2,'0')).join('').toUpperCase();
// Token do link: derivado de HMAC(código + segredo). Trocar ORDER_SECRET invalida todos os links.
const orderAccessToken=async(code,secret)=>{const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret||'fc-ordens'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(String(code)));return Array.from(new Uint8Array(signature)).slice(0,16).map(byte=>byte.toString(16).padStart(2,'0')).join('')};
const orderCleanCode=code=>String(code||'').toUpperCase().replace(/[^A-F0-9]/g,'').slice(0,16);
const escapeHtml=value=>String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function orderLines(briefing){const data=briefing||{};const cast=(Array.isArray(data.cast)?data.cast:[]).map(item=>cleanText(item&&item.name)+(item&&item.detail?' ('+cleanText(item.detail)+')':'')+(item&&item.kind?' · '+item.kind:'')).filter(Boolean);const dedication=(cleanText(data.dedicationTitle)?cleanText(data.dedicationTitle)+' · ':'')+(cleanText(data.dedication)||'sem dedicatória');return [['Criança',cleanText(data.name)],['Faixa etária',cleanText(data.age)+(data.years===''||data.years===undefined||data.years===null?'':' · '+data.years+' anos')],['Tema',cleanText(data.theme)],['Sentimento',cleanText(data.feeling)],['Estilo',cleanText(data.style)],['Objetivo',cleanText(data.objective)],['Elenco',cast.join(', ')||'somente a criança'],['Idioma',cleanText(data.language)],['Personagem',cleanText(data.gender)+(cleanText(data.personality)?' · '+cleanText(data.personality):'')],['Roupa',data.outfit==='original'?'manter a da foto':'roupa nova da aventura'],['Dedicatória',dedication],['Detalhes',cleanText(data.details)||'nenhum'],['E-mail',cleanText(data.email)]]}
function orderSummary(briefing,code,settings,link){const body=orderLines(briefing).filter(entry=>cleanText(entry[1])).map(entry=>'• '+entry[0]+': '+entry[1]);return ['*Pedido '+code+'* — '+settings.shop,'',...body,'','*Valor:* '+settings.price+(settings.pix?' · Pix: '+settings.pix:''),'*Pagamento:* combinado por aqui, no WhatsApp.','','📷 A foto escolhida e todos os dados estão neste link:','🔗 '+(link||orderLink(code,''))].join('\n')}
function orderLink(code,token){return '/pedido/'+encodeURIComponent(code)+(token?'?t='+encodeURIComponent(token):'')}
function orderWhatsAppLink(settings,summary){return settings.whatsapp?'https://wa.me/'+settings.whatsapp+'?text='+encodeURIComponent(summary):''}
async function orderIndex(env){const object=await env.BUCKET.get('orders/index.json');if(!object)return [];try{const list=await object.json();return Array.isArray(list)?list:[]}catch{return []}}
async function saveOrderRecord(env,record){await env.BUCKET.put('orders/'+record.code+'.json',JSON.stringify(record),{httpMetadata:{contentType:'application/json'}});const list=await orderIndex(env);list.unshift({code:record.code,accessToken:record.accessToken,createdAt:record.createdAt,name:record.briefing.name,status:record.status,total:record.total});await env.BUCKET.put('orders/index.json',JSON.stringify(list.slice(0,500)),{httpMetadata:{contentType:'application/json'}});return record}
async function readOrderRecord(env,code){const clean=orderCleanCode(code);if(!clean)return null;const object=await env.BUCKET.get('orders/'+clean+'.json');if(!object)return null;return object.json()}
async function deleteOrderRecord(env,code){const clean=orderCleanCode(code);if(!clean)return false;const existing=await env.BUCKET.get('orders/'+clean+'.json');if(!existing)return false;if(typeof env.BUCKET.delete==='function')await env.BUCKET.delete('orders/'+clean+'.json');const list=await orderIndex(env);await env.BUCKET.put('orders/index.json',JSON.stringify(list.filter(item=>item&&item.code!==clean)),{httpMetadata:{contentType:'application/json'}});return true}
async function uploadWhatsAppMedia(settings,jpegBytes){const form=new FormData();form.append('messaging_product','whatsapp');form.append('type','image/jpeg');form.append('file',new Blob([jpegBytes],{type:'image/jpeg'}),'foto-referencia.jpg');const response=await fetch('https://graph.facebook.com/v21.0/'+settings.phoneId+'/media',{method:'POST',headers:{authorization:'Bearer '+settings.token},body:form});if(!response.ok)throw new Error('WhatsApp recusou a imagem ('+response.status+')');const data=await response.json();return data.id}
async function sendOrderToWhatsApp(settings,summary,photo){if(!settings.token||!settings.phoneId||!settings.whatsapp)return {sent:false,reason:'Envio automático desligado'};const endpoint='https://graph.facebook.com/v21.0/'+settings.phoneId+'/messages';const headers={'content-type':'application/json',authorization:'Bearer '+settings.token};const jpeg=pdfJpegBytes(photo);if(jpeg){const mediaId=await uploadWhatsAppMedia(settings,jpeg);const uploaded=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify({messaging_product:'whatsapp',to:settings.whatsapp,type:'image',image:{id:mediaId}}