// worker/pdf.js — compositor de PDF A4 sem dependências (texto WinAnsi + JPEG embutido).
const PDF_PAGE={width:595.28,height:841.89,margin:56};
const PDF_INK={dark:'0.145 0.125 0.224 rg',violet:'0.451 0.267 0.839 rg',soft:'0.53 0.486 0.6 rg'};
const WINANSI_EXTRA={0x20ac:0x80,0x201a:0x82,0x0192:0x83,0x201e:0x84,0x2026:0x85,0x2020:0x86,0x2021:0x87,0x02c6:0x88,0x2030:0x89,0x0160:0x8a,0x2039:0x8b,0x0152:0x8c,0x017d:0x8e,0x2018:0x91,0x2019:0x92,0x201c:0x93,0x201d:0x94,0x2022:0x95,0x2013:0x96,0x2014:0x97,0x02dc:0x98,0x2122:0x99,0x0161:0x9a,0x203a:0x9b,0x0153:0x9c,0x017e:0x9e,0x0178:0x9f};
function pdfEncode(text){let out='';for(const char of String(text==null?'':text)){const code=char.codePointAt(0);if(code===9||code===10||code===13){out+=' ';continue}if(code>=32&&code<127){out+=char;continue}if(code>=160&&code<256){out+=String.fromCharCode(code);continue}const mapped=WINANSI_EXTRA[code];out+=mapped?String.fromCharCode(mapped):'?'}return out}
const pdfEscape=text=>pdfEncode(text).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const PDF_CHAR_WIDTH=0.5;
function pdfWrap(text,size,maxWidth){const maxChars=Math.max(6,Math.floor(maxWidth/(size*PDF_CHAR_WIDTH)));const lines=[];for(const paragraph of String(text==null?'':text).split(/\n+/)){const words=paragraph.split(/\s+/).filter(Boolean);if(!words.length){lines.push('');continue}let line='';for(const word of words){if(!line){line=word;continue}if((line+' '+word).length<=maxChars)line+=' '+word;else{lines.push(line);line=word}}lines.push(line)}return lines.length?lines:['']}
const PDF_JPEG_DATA_URL=/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/i;
function pdfJpegBytes(dataUrl){if(!PDF_JPEG_DATA_URL.test(String(dataUrl||'')))return null;const binary=atob(String(dataUrl).replace(/^data:image\/jpeg;base64,/i,''));const bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return bytes}
function pdfJpegSize(bytes){if(!bytes||bytes.length<10||bytes[0]!==0xff||bytes[1]!==0xd8)return null;let index=2;while(index+9<bytes.length){if(bytes[index]!==0xff){index++;continue}const marker=bytes[index+1];if(marker>=0xc0&&marker<=0xcf&&marker!==0xc4&&marker!==0xc8&&marker!==0xcc)return {height:(bytes[index+5]<<8)+bytes[index+6],width:(bytes[index+7]<<8)+bytes[index+8]};if(marker===0xd8||marker===0x01||(marker>=0xd0&&marker<=0xd7)){index+=2;continue}index+=2+((bytes[index+2]<<8)+bytes[index+3])}return null}
function pdfJpegImage(dataUrl){const bytes=pdfJpegBytes(dataUrl);if(!bytes)return null;const size=pdfJpegSize(bytes);if(!size)return null;let binary='';for(let index=0;index<bytes.length;index++)binary+=String.fromCharCode(bytes[index]);return {width:size.width,height:size.height,length:bytes.length,binary}}
function pdfToBytes(text){const bytes=new Uint8Array(text.length);for(let index=0;index<text.length;index++)bytes[index]=text.charCodeAt(index)&0xff;return bytes}
function pdfAssemble(objects){let out='%PDF-1.4\n';const offsets=[];objects.forEach((body,index)=>{offsets.push(out.length);out+=(index+1)+' 0 obj\n'+body+'\nendobj\n'});const startXref=out.length;out+='xref\n0 '+(objects.length+1)+'\n0000000000 65535 f \n';offsets.forEach(offset=>{out+=String(offset).padStart(10,'0')+' 00000 n \n'});out+='trailer\n<< /Size '+(objects.length+1)+' /Root 1 0 R /Producer (FC Livros Magicos) >>\nstartxref\n'+startXref+'\n%%EOF\n';return pdfToBytes(out)}
const pdfText=(text,x,y,size,font,color)=>'BT '+color+' /F'+font+' '+size+' Tf '+x.toFixed(2)+' '+y.toFixed(2)+' Tm ('+pdfEscape(text)+') Tj ET\n';
const pdfImage=(name,x,y,width,height)=>'q '+width.toFixed(2)+' 0 0 '+height.toFixed(2)+' '+x.toFixed(2)+' '+y.toFixed(2)+' cm /'+name+' Do Q\n';
const pdfRect=(x,y,width,height,color)=>'q '+color+' '+x.toFixed(2)+' '+y.toFixed(2)+' '+width.toFixed(2)+' '+height.toFixed(2)+' re f Q\n';
const pdfRule=(y,color)=>'q '+color+' 1.2 w '+PDF_PAGE.margin.toFixed(2)+' '+y.toFixed(2)+' m '+(PDF_PAGE.width-PDF_PAGE.margin).toFixed(2)+' '+y.toFixed(2)+' l S Q\n';
function pdfPage(spec){const contentWidth=PDF_PAGE.width-2*PDF_PAGE.margin;let cursorY=PDF_PAGE.height-PDF_PAGE.margin;let content='';const images=[];
if(spec.image){const scale=Math.min(contentWidth/spec.image.width,340/spec.image.height);const width=spec.image.width*scale;const height=spec.image.height*scale;cursorY-=height+18;content+=pdfImage('Im0',(PDF_PAGE.width-width)/2,cursorY,width,height);images.push(spec.image)}
else if(spec.placeholder){const height=132;cursorY-=height+18;content+=pdfRect(PDF_PAGE.margin,cursorY,contentWidth,height,'0.96 g');content+=pdfRect(PDF_PAGE.margin,cursorY,contentWidth,2,'0.85 0.8 0.92 rg');pdfWrap('Ilustração: '+spec.placeholder,9,contentWidth-24).slice(0,5).forEach((line,index)=>{content+=pdfText(line,PDF_PAGE.margin+12,cursorY+height-24-index*12,9,1,PDF_INK.soft)})}
if(spec.heading){const headingSize=spec.headingSize||20;pdfWrap(spec.heading,headingSize,contentWidth).forEach(line=>{cursorY-=headingSize>=20?26:18;content+=pdfText(line,PDF_PAGE.margin,cursorY,headingSize,spec.headingFont||2,PDF_INK.violet)});cursorY-=8;content+=pdfRule(cursorY,PDF_INK.violet);cursorY-=12}
const size=spec.bodySize||12;const lineHeight=size*1.45;let truncated=false;
for(const paragraph of spec.paragraphs||[]){for(const line of pdfWrap(paragraph,size,contentWidth)){if(cursorY-lineHeight<PDF_PAGE.margin+30){truncated=true;break}cursorY-=lineHeight;content+=pdfText(line,PDF_PAGE.margin,cursorY,size,1,PDF_INK.dark)}if(truncated)break;cursorY-=8}
if(spec.footer)content+=pdfText(spec.footer,PDF_PAGE.margin,PDF_PAGE.margin-26,9,3,PDF_INK.soft);
return {content,images}}
function composeBookPdf(briefing,story){const safeBriefing=briefing||{};const safeStory=story||{};const specs=[];
specs.push({heading:safeStory.title||'Livro personalizado',headingSize:26,paragraphs:[safeStory.subtitle||'',(safeBriefing.name||'')+' · '+(safeBriefing.age||'')+' · '+(safeBriefing.language||'')],image:pdfJpegImage(safeBriefing.photo),footer:'FC Livros Mágicos · gerado em '+new Date().toLocaleDateString('pt-BR')});
if(cleanText(safeStory.dedication))specs.push({heading:'Dedicatória',headingSize:18,paragraphs:[safeStory.dedication]});
(safeStory.pages||[]).forEach(page=>{const art=(safeStory.illustrations||[]).find(item=>item&&item.page===page.page);const image=art&&art.image?pdfJpegImage(art.image):null;specs.push({heading:'Página '+page.page,headingSize:14,paragraphs:[page.text],image,placeholder:image?null:(art?art.prompt:''),footer:'FC Livros Mágicos · página '+page.page+' de '+(safeStory.pages||[]).length})});
specs.push({heading:'Ficha de produção',headingSize:18,paragraphs:['Estas orientações não fazem parte do livro final: são os prompts para produzir as '+ILLUSTRATION_COUNT+' ilustrações.'].concat((safeStory.illustrations||[]).map(item=>'Página '+item.page+': '+item.prompt))});
const objects=['<< /Type /Catalog /Pages 2 0 R >>','','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique /Encoding /WinAnsiEncoding >>'];const kids=[];
for(const spec of specs){const {content,images}=pdfPage(spec);const resources=[];images.forEach((image,index)=>{objects.push('<< /Type /XObject /Subtype /Image /Width '+image.width+' /Height '+image.height+' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+image.length+' >>\nstream\n'+image.binary+'\nendstream');resources.push('/Im'+index+' '+objects.length+' 0 R')});objects.push('<< /Length '+content.length+' >>\nstream\n'+content+'\nendstream');kids.push(objects.length+1);objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '+PDF_PAGE.width+' '+PDF_PAGE.height+'] /Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R >> '+(resources.length?'/XObject << '+resources.join(' ')+' >> ':'')+'>> /Contents '+(objects.length)+' 0 R >>')}
objects[1]='<< /Type /Pages /Kids ['+kids.map(number=>number+' 0 R').join(' ')+'] /Count '+kids.length+' >>';
return pdfAssemble(objects)}
function pdfFileName(briefing){const slug=(cleanText(briefing&&briefing.name)||'livro').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase();return 'livro-'+(slug||'personalizado')+'.pdf'}