// worker/story.js — história de 30 páginas e 14 prompts de ilustração a partir do briefing.
// Provedores: mock (padrão, sem chave), openai, gemini e anthropic.
// Ambiente: AI_PROVIDER (mock|openai|gemini|anthropic), AI_API_KEY (ou OPENAI_API_KEY), AI_MODEL.
const STORY_PAGES=30;
const ILLUSTRATION_COUNT=14;
const AGE_RULES={'0 a 2 anos':{sentences:1,words:8,focus:'palavras do cotidiano, sons, repetição e muito afeto, sem conflito assustador'},'3 a 5 anos':{sentences:2,words:10,focus:'frases curtas, humor leve, repetição de sons e a criança participando da ação'},'6 a 9 anos':{sentences:3,words:14,focus:'aventura com diálogos, um obstáculo claro e solução construída pela criança'},'10+ anos':{sentences:4,words:18,focus:'narrativa mais longa, vocabulário rico, escolhas e consequências'}};
const AGE_DEFAULT={sentences:2,words:12,focus:'frases curtas e claras, com a criança no centro da ação'};
const STORY_BEATS=[['Apresentação','apresentar a criança na rotina e mostrar o que ela ama'],['O convite','um acontecimento desperta a curiosidade pelo mundo do tema'],['A travessia','a criança entra no cenário da aventura e conhece o lugar'],['O encontro','alguém se junta à jornada e propõe uma parceria'],['O obstáculo','surge um problema leve e adequado à idade'],['A tentativa','a criança tenta resolver e algo muda no caminho'],['A dúvida','a criança sente o sentimento escolhido e precisa decidir'],['A ideia','a criança encontra uma solução com a própria força'],['A conquista','a solução funciona com apoio do elenco, sem mágica'],['O reencontro','a história fecha voltando para casa com o que ficou no coração']];
const ILLUSTRATION_PAGES=[1,3,5,7,9,11,13,15,17,19,21,23,26,29];
const REQUIRED_BRIEFING=[['age','faixa etária'],['photo','foto da criança'],['theme','tema'],['feeling','sentimento'],['style','estilo'],['name','nome da criança'],['objective','objetivo'],['language','idioma']];
const cleanText=value=>typeof value==='string'?value.trim():'';
function requiredBriefingFields(briefing){const missing=REQUIRED_BRIEFING.filter(entry=>!cleanText(briefing&&briefing[entry[0]])).map(entry=>entry[1]);if(briefing&&briefing.years==='')missing.push('idade em anos');return missing}
function storyLanguage(language){return language==='English (US)'?'inglês (americano)':language==='Español (LatAm)'?'espanhol (América Latina)':'português do Brasil'}
function castLine(briefing){const cast=Array.isArray(briefing.cast)?briefing.cast.filter(item=>item&&cleanText(item.name)):[];if(!cast.length)return 'sem personagens extras';return cast.map(item=>item.name+' ('+cleanText(item.kind).toLowerCase()+(cleanText(item.detail)?', '+cleanText(item.detail):'')+')').join('; ')}
function storyContext(briefing){const age=AGE_RULES[briefing.age]||AGE_DEFAULT;return ['Protagonista: '+(cleanText(briefing.name)||'a criança'),'Faixa etária: '+(cleanText(briefing.age)||'não informada')+(briefing.years===''?'':' · idade informada: '+briefing.years+' anos'),'Ritmo: '+age.sentences+' frase(s) por página, cerca de '+age.words+' palavras por frase; '+age.focus,'Tema: '+(cleanText(briefing.theme)||'aventura'),'Sentimento/valor: '+(cleanText(briefing.feeling)||'amizade'),'Estilo visual: '+(cleanText(briefing.style)||'cartoon mágico'),'Roupa nas ilustrações: '+(briefing.outfit==='original'?'manter a roupa da foto de referência':'criar uma roupa nova e manter a mesma em todas as páginas'),'Personalidade: '+(cleanText(briefing.personality)||'curiosa e imaginativa'),'Elenco de apoio: '+castLine(briefing),'Objetivo da família: '+(cleanText(briefing.objective)||'não informado'),'Dedicatória: '+(cleanText(briefing.dedication)?(cleanText(briefing.dedicationTitle)?cleanText(briefing.dedicationTitle)+' · ':'')+cleanText(briefing.dedication):'sem dedicatória'),'Detalhes pedidos: '+(cleanText(briefing.details)||'nenhum'),'Idioma do texto: '+storyLanguage(briefing.language)].join('\n')}
function buildStoryPrompt(briefing){const age=AGE_RULES[briefing.age]||AGE_DEFAULT;return ['Você escreve livros infantis personalizados e responde apenas com JSON válido.','','DADOS DO LIVRO',storyContext(briefing),'','REGRAS','1. A criança é a protagonista e resolve o problema com as próprias ideias; amigos e adultos apoiam, nunca resolvem por ela.','2. Trabalhe a lição escolhida ('+(cleanText(briefing.feeling)||'amizade')+') mostrando na ação, sem explicar a moral de forma didática.','3. Nada de violência, medo excessivo, morte, marcas, preconceito, vilões assustadores ou qualquer conteúdo impróprio para a idade.','4. Cada página apresenta uma cena diferente, sem repetir a mesma abertura.','5. A dedicatória é única e aparece sozinha na primeira página, antes da história.','6. Escreva em '+storyLanguage(briefing.language)+' e mantenha o nome da criança exatamente como foi informado.','','FORMATO (JSON exato)','{"title":"título curto","subtitle":"frase de apoio com o nome da criança","dedication":"dedicatória ou string vazia","pages":[{"text":"texto da página"}],"illustrations":[{"page":1,"prompt":"descrição visual em inglês"}]}','- pages: exatamente '+STORY_PAGES+' itens na ordem de leitura, com '+age.sentences+' frase(s) por página.','- illustrations: exatamente '+ILLUSTRATION_COUNT+' itens. "page" indica em que página do livro a arte aparece e deve cobrir a capa e cenas distribuídas ao longo da história.','- Cada prompt de ilustração descreve cenário, ação, enquadramento e emoção, em estilo '+(cleanText(briefing.style)||'cartoon mágico')+', sempre lembrando que a identidade da criança deve ser preservada a partir da foto de referência e que a imagem não pode conter texto.'].join('\n')}
function mockPageLines(briefing){const name=cleanText(briefing.name)||'A criança';const theme=(cleanText(briefing.theme)||'aventura').toLowerCase();const feeling=(cleanText(briefing.feeling)||'amizade').toLowerCase();const friend=(Array.isArray(briefing.cast)&&briefing.cast[0]&&cleanText(briefing.cast[0].name))||'um novo amigo';return [`${name} acordou animado e pronto 